# Form implementation generated from reading ui file 'd:\Навчання\2 курс\2\course work\sign_in.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.signIn = QtWidgets.QLabel(parent=self.centralwidget)
        self.signIn.setGeometry(QtCore.QRect(0, 0, 450, 500))
        self.signIn.setText("")
        self.signIn.setPixmap(QtGui.QPixmap("d:\\Навчання\\2 курс\\2\\course work\\4a7eaeae52140c9205af389cc1e2c7b7-Enhanced-transformed (1).jpeg"))
        self.signIn.setObjectName("signIn")
        self.main_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.main_label.setGeometry(QtCore.QRect(200, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.main_label.setFont(font)
        self.main_label.setStyleSheet("background-color: rgb(149, 223, 223);")
        self.main_label.setObjectName("main_label")
        self.label_ph_num = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_ph_num.setGeometry(QtCore.QRect(10, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_ph_num.setFont(font)
        self.label_ph_num.setStyleSheet("background-color: rgb(149, 223, 223);")
        self.label_ph_num.setObjectName("label_ph_num")
        self.label_pass = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_pass.setGeometry(QtCore.QRect(80, 160, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_pass.setFont(font)
        self.label_pass.setStyleSheet("background-color: rgb(149, 223, 223);")
        self.label_pass.setObjectName("label_pass")
        self.back1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back1.setGeometry(QtCore.QRect(100, 280, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back1.setFont(font)
        self.back1.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.back1.setObjectName("back1")
        self.submit1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit1.setGeometry(QtCore.QRect(260, 280, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.submit1.setFont(font)
        self.submit1.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.submit1.setObjectName("submit1")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 110, 231, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 160, 231, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вхід"))
        self.main_label.setText(_translate("MainWindow", "Вхід"))
        self.label_ph_num.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_ph_num.setText(_translate("MainWindow", "Номер телефону"))
        self.label_pass.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_pass.setText(_translate("MainWindow", "Пароль"))
        self.back1.setText(_translate("MainWindow", "Назад"))
        self.submit1.setText(_translate("MainWindow", "Підтвердити"))
