# Form implementation generated from reading ui file 'd:\Навчання\2 курс\2\course work\start.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(parent=self.centralwidget)
        self.image.setGeometry(QtCore.QRect(0, 0, 450, 500))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("d:\\Навчання\\2 курс\\2\\course work\\4a7eaeae52140c9205af389cc1e2c7b7-Enhanced-transformed (1).jpeg"))
        self.image.setObjectName("image")
        self.name_of_app = QtWidgets.QLabel(parent=self.centralwidget)
        self.name_of_app.setGeometry(QtCore.QRect(130, 90, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.name_of_app.setFont(font)
        self.name_of_app.setStyleSheet("background-color: rgb(149, 223, 223);")
        self.name_of_app.setObjectName("name_of_app")
        self.btn_sign_in = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_sign_in.setGeometry(QtCore.QRect(74, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_sign_in.setFont(font)
        self.btn_sign_in.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.btn_sign_in.setObjectName("btn_sign_in")
        self.btn_sign_up = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_sign_up.setGeometry(QtCore.QRect(270, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_sign_up.setFont(font)
        self.btn_sign_up.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.btn_sign_up.setObjectName("btn_sign_up")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(0, 0, 451, 501))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.raise_()
        self.image.raise_()
        self.name_of_app.raise_()
        self.btn_sign_in.raise_()
        self.btn_sign_up.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вступні іспити"))
        self.name_of_app.setText(_translate("MainWindow", "Вступні іспити"))
        self.btn_sign_in.setText(_translate("MainWindow", "Вхід"))
        self.btn_sign_up.setText(_translate("MainWindow", "Реєстрація"))
